#!/bin/bash

RANDOM_NB=$((1024 + RANDOM % 48000))
echo "Use random base port $RANDOM_NB"

cat <<EOF > ".env"
NGINX_PORT=$((RANDOM_NB))

DEV_API_PORT=$((RANDOM_NB + 10))
DEV_UI_PORT=$((RANDOM_NB + 11))
DEV_PORTAL_PORT=$((RANDOM_NB + 12))
DEV_OBSERVER_PORT=$((RANDOM_NB + 13))
MAILDEV_UI_PORT=$((RANDOM_NB + 14))
MAILDEV_SMTP_PORT=$((RANDOM_NB + 15))
DEV_INGRESS_PORT=$((RANDOM_NB + 16))

MONGO_PORT=$((RANDOM_NB + 20))
ES_PORT=$((RANDOM_NB + 21))

SD_PORT=$((RANDOM_NB + 30))
DF_PORT=$((RANDOM_NB + 31))
EVENTS_PORT=$((RANDOM_NB + 32))
PROCESSINGS_PORT=$((RANDOM_NB + 33))
EOF