/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorsPreview: typeof import('./../src/components/portal-edit/colors-preview.vue')['default']
    FontFamiliesPreview: typeof import('./../src/components/portal-edit/font-families-preview.vue')['default']
    ImageUpload: typeof import('./../src/components/image-upload.vue')['default']
    LayoutAppBar: typeof import('./../../portal/app/components/layout/layout-app-bar.vue')['default']
    LayoutHeader: typeof import('./../../portal/app/components/layout/layout-header.vue')['default']
    LayoutHeaderLogo: typeof import('./../../portal/app/components/layout/layout-header-logo.vue')['default']
    NavMenu: typeof import('./../../portal/app/components/nav/nav-menu.vue')['default']
    NavTabs: typeof import('./../../portal/app/components/nav/nav-tabs.vue')['default']
    NavTabsOrMenu: typeof import('./../../portal/app/components/nav/nav-tabs-or-menu.vue')['default']
    PageCard: typeof import('./../src/components/page/page-card.vue')['default']
    PageEditElements: typeof import('./../src/components/page-edit/page-edit-elements.vue')['default']
    PageEditPublication: typeof import('./../src/components/page-edit/page-edit-publication.vue')['default']
    PageElement: typeof import('./../../portal/app/components/page/page-element.vue')['default']
    PageElementAlert: typeof import('./../../portal/app/components/page/page-element-alert.vue')['default']
    PageElementCard: typeof import('./../../portal/app/components/page/page-element-card.vue')['default']
    PageElementDivider: typeof import('./../../portal/app/components/page/page-element-divider.vue')['default']
    PageElementImage: typeof import('./../../portal/app/components/page/page-element-image.vue')['default']
    PageElements: typeof import('./../../portal/app/components/page/page-elements.vue')['default']
    PageElementTabs: typeof import('./../../portal/app/components/page/page-element-tabs.vue')['default']
    PageElementText: typeof import('./../../portal/app/components/page/page-element-text.vue')['default']
    PageElementTitle: typeof import('./../../portal/app/components/page/page-element-title.vue')['default']
    PageElementTwoColumns: typeof import('./../../portal/app/components/page/page-element-two-columns.vue')['default']
    PagePreviewElement: typeof import('./../src/components/page-edit/page-preview-element.vue')['default']
    PagesActions: typeof import('./../src/components/pages-actions.vue')['default']
    PortalActions: typeof import('./../src/components/portal/portal-actions.vue')['default']
    PortalCard: typeof import('./../src/components/portal/portal-card.vue')['default']
    PortalsActions: typeof import('./../src/components/portals-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VjsfPageConfig: typeof import('./../src/components/vjsf/vjsf-page-config.vue')['default']
    VjsfPageElements: typeof import('./../src/components/vjsf/vjsf-page-elements.vue')['default']
    VjsfPortalConfig: typeof import('./../src/components/vjsf/vjsf-portal-config.vue')['default']
    VjsfPortalIngress: typeof import('./../src/components/vjsf/vjsf-portal-ingress.vue')['default']
  }
}
