/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBtn: typeof import('./../../portal/app/components/action-btn.vue')['default']
    ApplicationCard: typeof import('./../../portal/app/components/application/application-card.vue')['default']
    ApplicationMetadata: typeof import('./../../portal/app/components/application/application-metadata.vue')['default']
    ApplicationPreview: typeof import('./../../portal/app/components/application/application-preview.vue')['default']
    DatasetAttachments: typeof import('./../../portal/app/components/dataset/dataset-attachments.vue')['default']
    DatasetCard: typeof import('./../../portal/app/components/dataset/dataset-card.vue')['default']
    DatasetDownload: typeof import('./../../portal/app/components/dataset/dataset-download.vue')['default']
    DatasetMapPreview: typeof import('./../../portal/app/components/dataset/dataset-map-preview.vue')['default']
    DatasetMetadata: typeof import('./../../portal/app/components/dataset/dataset-metadata.vue')['default']
    DatasetSchema: typeof import('./../../portal/app/components/dataset/dataset-schema.vue')['default']
    DatasetTablePreview: typeof import('./../../portal/app/components/dataset/dataset-table-preview.vue')['default']
    'DFrameWrapper.client': typeof import('./../../portal/app/components/d-frame-wrapper.client.vue')['default']
    IconBluesky: typeof import('./../../portal/app/components/icon/icon-bluesky.vue')['default']
    IconX: typeof import('./../../portal/app/components/icon/icon-x.vue')['default']
    LayoutAppBar: typeof import('./../../portal/app/components/layout/layout-app-bar.vue')['default']
    LayoutFooter: typeof import('./../../portal/app/components/layout/layout-footer.vue')['default']
    LayoutFullAppBar: typeof import('./../../portal/app/components/layout/layout-full-app-bar.vue')['default']
    LayoutHeader: typeof import('./../../portal/app/components/layout/layout-header.vue')['default']
    LayoutHeaderLogo: typeof import('./../../portal/app/components/layout/layout-header-logo.vue')['default']
    LayoutPersonalAppBar: typeof import('./../../portal/app/components/layout/layout-personal-app-bar.vue')['default']
    LayoutPersonalMenu: typeof import('./../../portal/app/components/layout/layout-personal-menu.vue')['default']
    LayoutPersonalNavigation: typeof import('./../../portal/app/components/layout/layout-personal-navigation.vue')['default']
    LayoutPreview: typeof import('./../../portal/app/components/layout/layout-preview.vue')['default']
    LayoutScrollToTop: typeof import('./../../portal/app/components/layout/layout-scroll-to-top.vue')['default']
    NavLink: typeof import('./../../portal/app/components/nav/nav-link.vue')['default']
    NavMenu: typeof import('./../../portal/app/components/nav/nav-menu.vue')['default']
    NavTabs: typeof import('./../../portal/app/components/nav/nav-tabs.vue')['default']
    NavTabsMenuItem: typeof import('./../../portal/app/components/nav/nav-tabs-menu-item.vue')['default']
    NavTabsOrMenu: typeof import('./../../portal/app/components/nav/nav-tabs-or-menu.vue')['default']
    NotificationQueue: typeof import('./../../portal/app/components/notification-queue.vue')['default']
    PageElement: typeof import('./../../portal/app/components/page/page-element.vue')['default']
    PageElementAlert: typeof import('./../../portal/app/components/page/page-element-alert.vue')['default']
    PageElementCard: typeof import('./../../portal/app/components/page/page-element-card.vue')['default']
    PageElementContact: typeof import('./../../portal/app/components/page/page-element-contact.vue')['default']
    PageElementDivider: typeof import('./../../portal/app/components/page/page-element-divider.vue')['default']
    PageElementImage: typeof import('./../../portal/app/components/page/page-element-image.vue')['default']
    PageElements: typeof import('./../../portal/app/components/page/page-elements.vue')['default']
    PageElementTabs: typeof import('./../../portal/app/components/page/page-element-tabs.vue')['default']
    PageElementText: typeof import('./../../portal/app/components/page/page-element-text.vue')['default']
    PageElementTitle: typeof import('./../../portal/app/components/page/page-element-title.vue')['default']
    PageElementTwoColumns: typeof import('./../../portal/app/components/page/page-element-two-columns.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./../../portal/app/components/social-links.vue')['default']
    SocialShare: typeof import('./../../portal/app/components/social-share.vue')['default']
    TopicsFacets: typeof import('./../../portal/app/components/topics-facets.vue')['default']
  }
}
