/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dev': RouteRecordInfo<'/dev', '/dev', Record<never, never>, Record<never, never>>,
    '/pages/': RouteRecordInfo<'/pages/', '/pages', Record<never, never>, Record<never, never>>,
    '/pages/[groupId]/': RouteRecordInfo<'/pages/[groupId]/', '/pages/:groupId', { groupId: ParamValue<true> }, { groupId: ParamValue<false> }>,
    '/pages/[groupId]/[pageId]': RouteRecordInfo<'/pages/[groupId]/[pageId]', '/pages/:groupId/:pageId', { groupId: ParamValue<true>, pageId: ParamValue<true> }, { groupId: ParamValue<false>, pageId: ParamValue<false> }, '/pages/[groupId]/[pageId]/' | '/pages/[groupId]/[pageId]/edit-config'>,
    '/pages/[groupId]/[pageId]/': RouteRecordInfo<'/pages/[groupId]/[pageId]/', '/pages/:groupId/:pageId', { groupId: ParamValue<true>, pageId: ParamValue<true> }, { groupId: ParamValue<false>, pageId: ParamValue<false> }>,
    '/pages/[groupId]/[pageId]/edit-config': RouteRecordInfo<'/pages/[groupId]/[pageId]/edit-config', '/pages/:groupId/:pageId/edit-config', { groupId: ParamValue<true>, pageId: ParamValue<true> }, { groupId: ParamValue<false>, pageId: ParamValue<false> }>,
    '/pages/[groupId]/new': RouteRecordInfo<'/pages/[groupId]/new', '/pages/:groupId/new', { groupId: ParamValue<true> }, { groupId: ParamValue<false> }>,
    '/portals/': RouteRecordInfo<'/portals/', '/portals', Record<never, never>, Record<never, never>>,
    '/portals/[id]/': RouteRecordInfo<'/portals/[id]/', '/portals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portals/[id]/ingress': RouteRecordInfo<'/portals/[id]/ingress', '/portals/:id/ingress', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
