/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dev': RouteRecordInfo<'/dev', '/dev', Record<never, never>, Record<never, never>>,
    '/pages/': RouteRecordInfo<'/pages/', '/pages', Record<never, never>, Record<never, never>>,
    '/pages/[id]': RouteRecordInfo<'/pages/[id]', '/pages/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, '/pages/[id]/' | '/pages/[id]/edit-config'>,
    '/pages/[id]/': RouteRecordInfo<'/pages/[id]/', '/pages/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pages/[id]/edit-config': RouteRecordInfo<'/pages/[id]/edit-config', '/pages/:id/edit-config', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portals/': RouteRecordInfo<'/portals/', '/portals', Record<never, never>, Record<never, never>>,
    '/portals/[id]/': RouteRecordInfo<'/portals/[id]/', '/portals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/portals/[id]/ingress': RouteRecordInfo<'/portals/[id]/ingress', '/portals/:id/ingress', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
