// GENERATED FILE — DO NOT EDIT
// Regenerate with: npx tsx build/markup/generate-grammar.ts

// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Element = 2,
  SelfClosingTag = 5,
  TagName = 6,
  Name = 7,
  Attribute = 8,
  AttributeName = 9,
  AttributeValue = 11,
  String = 12,
  OpenTag = 14,
  CloseTag = 16,
  Text = 17
