// GENERATED FILE — DO NOT EDIT
// Regenerate with: npx tsx build/markup/generate-grammar.ts

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hQVQPOOO_QQO'#CaOOQO'#C^'#C^OdQPO'#C^OOQO'#Cn'#CnQVQPOOOOQO'#Cb'#CbOoQQO,58{O_QQO'#ClOOQO,58x,58xOdQPO,58xOOQO-E6l-E6lOOQO'#Ce'#CeOzQQO'#CdOOQO'#Co'#CoO!YQQO1G.gOOQO1G.g1G.gOOQO1G.p1G.pO!eQQO,59WOOQO1G.d1G.dO!jQQO,59OOOQO-E6m-E6mOOQO7+$R7+$ROOQO7+$[7+$[OOQO1G.r1G.rOOQO'#Cg'#CgOOQO1G.j1G.j",
  stateData: "!u~OfOS~OSPOaSO~OVUO~OSPO_WOaSO~OR`OV[O]aO~OYdORWXVWX]WX~ORfOV[O]gO~O]hO~O[iO~O_RS]S~",
  goto: "!pdPPePPkqPw{P!PPP!SP!YP!`!jXSORTYXQORTYQVPRbWT^V_T]V_RjdXRORTYQXRRcYQTOQYRTZTYQ_VRe_",
  nodeNames: "⚠ Document Element /> < SelfClosingTag TagName Name Attribute AttributeName = AttributeValue String > OpenTag </ CloseTag Text",
  maxTerm: 22,
  nodeProps: [
    ["openedBy", 3,"<",13,"< </"],
    ["closedBy", 4,"/> >",15,">"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "+`~RhOX!mXY#UYZ#UZ]!m]^#U^p!mpq#Uqr!mrs#gs!P!m!P!Q'd!Q!^!m!^!_(`!_!`(m!`!a)Q!a!c!m!c!})e!}#R!m#R#S)e#S#T!m#T#o)e#o;'S!m;'S;=`#O<%lO!mP!rSaPO!^!m!_;'S!m;'S;=`#O<%lO!mP#RP;=`<%l!m~#ZSf~XY#UYZ#U]^#Upq#UR#lXaPOr#grs$Xs!^#g!^!_$l!_#O#g#O#P&Y#P;'S#g;'S;=`'^<%lO#gR$`S[QaPO!^!m!_;'S!m;'S;=`#O<%lO!mQ$oVOr$lrs%Us#O$l#O#P%Z#P;'S$l;'S;=`&S<%lO$lQ%ZO[QQ%^RO;'S$l;'S;=`%g;=`O$lQ%jWOr$lrs%Us#O$l#O#P%Z#P;'S$l;'S;=`&S;=`<%l$l<%lO$lQ&VP;=`<%l$lR&_UaPO!^#g!^!_$l!_;'S#g;'S;=`&q;=`<%l$l<%lO#gR&tWOr$lrs%Us#O$l#O#P%Z#P;'S$l;'S;=`&S;=`<%l#g<%lO$lR'aP;=`<%l#gR'iUaPO!^!m!_!`!m!`!a'{!a;'S!m;'S;=`#O<%lO!mR(SSaPRQO!^!m!_;'S!m;'S;=`#O<%lO!m~(ePS~!P!Q(h~(mO_~R(tSYQaPO!^!m!_;'S!m;'S;=`#O<%lO!mR)XSaP]QO!^!m!_;'S!m;'S;=`#O<%lO!mR)l_VQaPO}!m}!O)e!O!P*k!P!Q!m!Q![)e![!^!m!_!c!m!c!})e!}#R!m#R#S)e#S#T!m#T#o)e#o;'S!m;'S;=`#O<%lO!mR*pYaPO!^!m!_!c!m!c!})e!}#R!m#R#S)e#S#T!m#T#o)e#o;'S!m;'S;=`#O<%lO!m",
  tokenizers: [0, 1],
  topRules: {"Document":[0,1]},
  tokenPrec: 77
})
