/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageCard: typeof import('./src/components/page/page-card.vue')['default']
    PageEditElements: typeof import('./src/components/page-edit/page-edit-elements.vue')['default']
    PageElement: typeof import('./src/components/page/page-element.vue')['default']
    PageElementCard: typeof import('./src/components/page/page-element-card.vue')['default']
    PageElementText: typeof import('./src/components/page/page-element-text.vue')['default']
    PageElementTitle: typeof import('./src/components/page/page-element-title.vue')['default']
    PagePreviewElement: typeof import('./src/components/page-edit/page-preview-element.vue')['default']
    PagesActions: typeof import('./src/components/pages-actions.vue')['default']
    PortalCard: typeof import('./src/components/portal/portal-card.vue')['default']
    PortalsActions: typeof import('./src/components/portals-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VjsfPageConfig: typeof import('./src/components/vjsf/vjsf-page-config.vue')['default']
    VjsfPageElements: typeof import('./src/components/vjsf/vjsf-page-elements.vue')['default']
  }
}
